version: '2'

# services:
#   db:
#     container_name: db
#     image: million12/mariadb
#     environment:
#       MARIADB_USER: niels
#       MARIADB_PASS: Welkom01!

#   cacti:
#     container_name: cacti-server
#     image: polinux/cacti
#     ports:
#       - "80:80"
#       #- "81:81"
#       #- "443:443"
#     environment:
#       DB_USER: niels
#       DB_PASS: Welkom01!
#       DB_ADDRESS: db

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Welkom01!
      - MYSQL_PASSWORD=Welkom01!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=Welkom01!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db